version: '3'

vars:
  IMG: ttl.sh/d3vlo0p/timeterra-operator:1h
  PLATFROMS: linux/arm64,linux/amd64

tasks:
  update:
    cmds:
      - make generate
      - make manifests
      
  run:
    env:
      AWS_PROFILE: timeterra
    cmds:
      - make install run

  deploy-to-k8s:
    cmds:
      - make deploy IMG="{{.IMG}}"

  dockerx-build-push:
    cmds:
      - make docker-buildx PLATFORMS="{{.PLATFROMS}}" IMG="{{.IMG}}"