version: '3'

includes:
  op: ./Taskfile.operator.yml
  chart: ./Taskfile.chart.yml
  dagger: ./Taskfile.dagger.yml

vars:
  PLATFORMS: linux/amd64
  IMG: d3vlo0p/timeterra-operator
  REPO: ttl.sh
  GH_REPO: ghcr.io
  VERSION: "0.4.3"
  CHART_REPO: oci://ttl.sh/d3vlo0p
  GH_CHART_REPO: oci://ghcr.io/d3vlo0p
  CHART_VERSION: "0.4.3"

tasks:
  build-deploy:
    cmds: 
      - task: op:build-push
      - task: chart:deploy
        vars:
          CHART_REPO: "./helm-charts"

  publish:
    cmds:
      - task: op:build-push
      - task: chart:publish

  deploy:
    cmds:
      - task: chart:deploy

  publish-release:
    vars:
      REPO: "{{.GH_REPO}}"
      CHART_REPO: "{{.GH_CHART_REPO}}"
      PLATFORMS: linux/arm64,linux/amd64
    cmds:
      - task: op:build-push
      - task: chart:publish

  deploy-release:
    cmds:
      - task: chart:deploy
        vars:
          REPO: "{{.GH_REPO}}"
          CHART_REPO: "{{.GH_CHART_REPO}}"

  undeploy:
    cmds:
      - task: chart:undeploy