version: '3'

includes:
  op: ./Taskfile.operator.yml
  chart: ./Taskfile.chart.yml
  dagger: ./Taskfile.dagger.yml

vars:
  PLATFROMS: linux/amd64
  REPO: ttl.sh
  IMG: d3vlo0p/timeterra-operator
  VERSION: "0.3.1"
  CHART_VERSION: "0.3.1"
  TAG: 1h

tasks:
  build-deploy:
    cmds: 
      - task: op:build-push
      - task: chart:deploy

  publish-operator:
    cmds: 
      - task: op:build-push
        vars:
          REPO: ghcr.io
          TAG: "{{.VERSION}}"
          PLATFROMS: linux/arm64,linux/amd64
  
  publish-chart:
    cmds:
      - task: chart:publish
        vars:
          CHART_REPO: oci://ghcr.io/d3vlo0p

  publish:
    cmds:
      - task: publish-operator
      - task: publish-chart

  deploy-rel:
    cmds:
      - kubectl apply --server-side -f ./helm-charts/timeterra/crds/
      - helm upgrade -n timeterra --create-namespace --install operator oci://ghcr.io/d3vlo0p/timeterra

  undeploy-rel:
    cmds:
      - task: chart:undeploy