version: '3'

vars:
  PLATFROMS: linux/amd64
  IMG: ttl.sh/d3vlo0p/timeterra-operator
  TAG: 1h

tasks:
  update:
    cmds:
      - make generate
      - make manifests
      
  run:
    env:
      AWS_PROFILE: timeterra
    cmds:
      - make install run
  
  dockerx-build-push:
    cmds:
      - make docker-buildx PLATFORMS="{{.PLATFROMS}}" IMG="{{.IMG}}:{{.TAG}}"

  k8s-depoly:
    cmds:
      - make deploy IMG="{{.IMG}}"

  k8s-undeploy:
    cmds:
      - make undeploy

  helm-depoly:
    cmds:
      - task: dockerx-build-push
      - kubectl apply -f ./config/crd/bases/*.yaml
      - helm upgrade -n timeterra --create-namespace --install operator ./helm-charts/time-terra --set image.repository={{.IMG}} --set image.tag={{.TAG}}

  helm-undepoly:
    cmds:
      - helm uninstall -n timeterra operator
      - kubectl delete -f ./config/crd/bases/*.yaml
      - kubectl delete namespace timeterra

  githhub-pub:
    cmds: 
      - task: dockerx-build-push
        vars:
          IMG: ghcr.io/d3vlo0p/timeterra
          TAG: 0.0.1
          PLATFROMS: linux/arm64,linux/amd64