version: '3'

vars:
  IMG: ttl.sh/d3vlo0p/timeterra-operator:1h
  PLATFROMS: linux/arm64,linux/amd64

tasks:
  update:
    cmds:
      - make generate
      - make manifests
      
  run:
    cmds:
      - make install run

  deploy-to-k8s:
    cmds:
      - make deploy IMG="{{.IMG}}"

  docker-build:
    cmds:
      - make docker-buildx PLATFORMS="{{.PLATFROMS}}" docker-push IMG="{{.IMG}}"

  create-aurora-cluster:
    env:
      AWS_ENDPOINT_URL: http://s3.localhost
    cmds:
      - awslocal rds create-db-cluster --db-cluster-identifier db1 --engine aurora-postgresql --database-name test --master-username myuser --master-user-password mypassword
      # - awslocal rds wait db-cluster-available --db-cluster-identifier db1
      # - awslocal rds describe-db-clusters --db-cluster-identifier db1
      # - awslocal rds create-db-instance --db-instance-identifier db1-instance --db-cluster-identifier db1 --engine aurora-postgresql --db-instance-class db.t3.large

