version: '3'

vars:
  PLATFROMS: linux/amd64
  IMG: ttl.sh/d3vlo0p/timeterra-operator
  TAG: 1h
  CHART_VERSION: "0.0.1"

tasks:
  update:
    cmds:
      - make generate
      - make manifests
      
  run:
    env:
      AWS_PROFILE: timeterra
    cmds:
      - make install run
  
  dockerx-build-push:
    cmds:
      - make docker-buildx PLATFORMS="{{.PLATFROMS}}" IMG="{{.IMG}}:{{.TAG}}"

  k8s-depoly:
    cmds:
      - make deploy IMG="{{.IMG}}"

  k8s-undeploy:
    cmds:
      - make undeploy

  helm-build:
    cmds:
      - helm package ./helm-charts/timeterra

  helm-deploy:
    cmds:
      - kubectl apply -f ./config/crd/bases
      - helm upgrade -n timeterra --create-namespace --install operator ./helm-charts/timeterra --set image.repository={{.IMG}} --set image.tag={{.TAG}}
  
  helm-deploy-build:
    cmds: 
      - task: dockerx-build-push
      - task: helm-deploy

  helm-undeploy:
    cmds:
      - helm uninstall -n timeterra operator
      - kubectl delete -f ./config/crd/bases
      - kubectl delete namespace timeterra

  githhub-pub:
    cmds: 
      - task: dockerx-build-push
        vars:
          IMG: ghcr.io/d3vlo0p/timeterra
          TAG: 0.0.1
          PLATFROMS: linux/arm64,linux/amd64
  
  githhub-pub-helm:
    cmds:
      - task: helm-build
      - helm push timeterra-{{.CHART_VERSION}}.tgz oci://ghcr.io/d3vlo0p
      - rm timeterra-{{.CHART_VERSION}}.tgz