# permissions for end users to view awsdocumentdbclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsdocumentdbcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: timeterra
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
  name: awsdocumentdbcluster-viewer-role
rules:
- apiGroups:
  - core.timeterra.d3vlo0p.dev
  resources:
  - awsdocumentdbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.timeterra.d3vlo0p.dev
  resources:
  - awsdocumentdbclusters/status
  verbs:
  - get
