# permissions for end users to view awsec2instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsec2instance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: timeterra
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
  name: awsec2instance-viewer-role
rules:
- apiGroups:
  - timeterra.d3vlo0p.dev
  resources:
  - awsec2instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - timeterra.d3vlo0p.dev
  resources:
  - awsec2instances/status
  verbs:
  - get
