# permissions for end users to view schedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: schedule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: timeterra
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
  name: schedule-viewer-role
rules:
- apiGroups:
  - timeterra.d3vlo0p.dev
  resources:
  - schedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - timeterra.d3vlo0p.dev
  resources:
  - schedules/status
  verbs:
  - get
