apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws_ec2_instance.yaml
  - aws_transfer_family.yaml
  - aws_rds_aurora.yaml
  - aws_documentdb.yaml
  - credentials_secret.yaml

