apiVersion: core.timeterra.d3vlo0p.dev/v1alpha1
kind: K8sPodReplicas
metadata:
  labels:
    app.kubernetes.io/name: k8spodreplicas
    app.kubernetes.io/instance: k8spodreplicas-sample
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: timeterra
  name: k8spodreplicas-sample
spec:
  actions:
    scalein:
      replicas: 1
    scaleup:
      replicas: 2
  enabled: true
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  namespaces:
    - default
  resourceType: Deployment
  schedule: schedule-sample
