apiVersion: core.timeterra.d3vlo0p.dev/v1alpha1
kind: NotificationPolicy
metadata:
  labels:
    app.kubernetes.io/name: timeterra
    app.kubernetes.io/managed-by: kustomize
  name: notificationpolicy-sample
spec:
  # TODO(user): Add fields here
