apiVersion: core.timeterra.d3vlo0p.dev/v1alpha1
kind: AwsRdsAuroraCluster
metadata:
  labels:
    app.kubernetes.io/name: awsrdsauroracluster
    app.kubernetes.io/instance: awsrdsauroracluster-sample
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: timeterra
  name: awsrdsauroracluster-sample
spec:
  # TODO(user): Add fields here
