apiVersion: core.timeterra.d3vlo0p.dev/v1alpha1
kind: K8sRunJob
metadata:
  labels:
    app.kubernetes.io/name: k8srunjob
    app.kubernetes.io/instance: k8srunjob-sample
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: timeterra
  name: k8srunjob-sample
spec:
  # TODO(user): Add fields here
