apiVersion: timeterra.d3vlo0p.dev/v1alpha1
kind: K8sRunJob
metadata:
  labels:
    app.kubernetes.io/name: k8srunjob
    app.kubernetes.io/instance: k8srunjob-sample
    app.kubernetes.io/part-of: timeterra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: timeterra
  name: k8srunjob-sample
spec:
  enabled: true
  schedule: schedule-sample
  namespaces:
    - default
  actions:
    scalein:
      job:
        ttlSecondsAfterFinished: 300
        template:
          spec:
            containers:
              - name: demo-job
                image: busybox:latest
                command: ["/bin/sh", "-c", "echo 'Action scalein';"]
            restartPolicy: OnFailure
    scaleup:
      job:
        ttlSecondsAfterFinished: 300
        template:
          spec:
            containers:
              - name: demo-job
                image: busybox:latest
                command: ["/bin/sh", "-c", "echo 'Action scaleup';"]
            restartPolicy: OnFailure