apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "timeterra.fullname" . }}-election-rolebinding
  labels:
    {{- include "timeterra.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "timeterra.fullname" . }}-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "timeterra.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
