apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "timeterra.fullname" . }}-role
  labels:
    {{- include "timeterra.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get